version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: file-manage-db
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USERNAME}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    networks:
      - goals-net
    volumes:
      - .docker/db/postgresql:/var/lib/postgresql/data
    restart: always

  file-manage:
    image: file-manage:latest
    build:
      context: ./
      target: development
      dockerfile: Dockerfile
    container_name: file-manage-app
    ports:
      - ${API_PORT}:${API_PORT}
    networks:
      - goals-net
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped

networks:
  goals-net:
